// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete.sql

package database

import (
	"context"
)

const cleanTable = `-- name: CleanTable :exec
DELETE FROM users
`

func (q *Queries) CleanTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanTable)
	return err
}
